# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Lily58'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["lily58_left","lily58_right"]'
      alphas: '["default"]'
      nav: '["default"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR\n#define MIRYOKU_KLUDGE_SOFT_OFF"]'
      extra: '["default"]'
      tap: '["default"]'
      clipboard: '["default"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_PM_SOFT_OFF=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll"]'
      modules: '["default"]'
