# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Lily58'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["lily58_left","lily58_right"]'
      alphas: '["default"]'
      nav: '["default"]'
      layers: '["default"]'
      extra: '["default"]'
      tap: '["default"]'
      clipboard: '["default"]'
